version: '3.3'
services:
  db-food:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
  web-food:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: daryamalysheva/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/backend_staticfiles/
      - media_value:/app/backend_mediafiles/
    depends_on:
      - db-food
    env_file:
      - .env
  frontend: 
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: daryamalysheva/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/backend_staticfiles/
      - media_value:/usr/share/nginx/html/backend_mediafiles/
    depends_on:
      - web-food
volumes:
  static_value:
  media_value: